INNOTEC-Proyect/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using ML;

namespace INNOTEC_Proyect.Controllers
{
    [Route("Usuario")]
    public class AdminController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly IConfiguration _configuration;

        public AdminController(HttpClient httpClient, IConfiguration configuration)
        {
            _httpClient = httpClient;
            _configuration = configuration;
            _httpClient.BaseAddress = new Uri(_configuration["UrlAPI"]);
        }

        [HttpGet("Index")]
        public async Task<IActionResult> Index()
        {
            var usuarios = await _httpClient.GetFromJsonAsync<List<Usuario>>("Usuario/GetAll");
            return View(usuarios);
        }

        [HttpGet("GetById")]
        public async Task<IActionResult> GetById(int id)
        {
            var usuario = await _httpClient.GetFromJsonAsync<Usuario>($"Usuario/GetById?id={id}");
            if (usuario != null)
            {
                return Json(new { success = true, data = usuario });
            }
            return Json(new { success = false });
        }

        [HttpPost("Insert")]
        public async Task<IActionResult> CreateUsuario(Usuario usuario)
        {
            var response = await _httpClient.PostAsJsonAsync("Usuario/Insert", usuario);
            if (response.IsSuccessStatusCode)
            {
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }

        [HttpPut("Update")]
        public async Task<IActionResult> UpdateUsuario(int id, Usuario usuario)
        {
            var response = await _httpClient.PutAsJsonAsync($"Usuario/Update?id={id}", usuario);
            if (response.IsSuccessStatusCode)
            {
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }

        [HttpDelete("Delete")]
        public async Task<IActionResult> DeleteUsuario(int id)
        {
            var response = await _httpClient.DeleteAsync($"Usuario/Delete?id={id}");
            if (response.IsSuccessStatusCode)
            {
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }
    }
}

INNOTEC-Proyect/Controllers/EnvioController.cs
using INNOTEC_Proyect.Models;
using MercadoPago.Client.Preference;
using MercadoPago.Config;
using MercadoPago.Resource.Preference;
using Microsoft.AspNetCore.Mvc;
using ML;
using Newtonsoft.Json;



namespace INNOTEC_Proyect.Controllers
{
    public class EnvioController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IWebHostEnvironment _environment;
        private readonly IHttpClientFactory _httpClientFactory;
        public int Cantidad { get; set; }
        public decimal Total { get; set; }
        public EnvioController(IConfiguration configuration, IWebHostEnvironment hostingEnvironment, IHttpClientFactory httpClientFactory)
        {
            _configuration = configuration;
            _environment = hostingEnvironment;
            _httpClientFactory = httpClientFactory;
        }

        public IActionResult Index(string idCompra, string idsCompra, decimal? total, int? cantidad)
        {
            List<int> listaIdsCompra = new List<int>();

            if (!string.IsNullOrEmpty(idCompra))
            {
                if (int.TryParse(idCompra, out int parsedId))
                {
                    listaIdsCompra.Add(parsedId);
                }
            }

            if (!string.IsNullOrEmpty(idsCompra))
            {
                listaIdsCompra.AddRange(idsCompra.Split(',').Select(id =>
                {
                    int.TryParse(id, out int parsedId);
                    return parsedId;
                }).Where(id => id != 0).ToList());
            }

            Cantidad = cantidad ?? 0;
            Total = total ?? 0;

            var pedidos = listaIdsCompra.Select(id => new Pedido
            {
                IdCompra = id
            }).ToList();

            var viewModel = new EnvioPedidoViewModel
            {
                Envios = listaIdsCompra.Select(id => new Envio { IdCompra = id }).ToList(),
                Pedidos = pedidos,
                Total = total ?? 0
            };

            // Guardar valores en la sesión
            HttpContext.Session.SetInt32("Cantidad", Cantidad);
            HttpContext.Session.SetString("Total", Total.ToString());
            HttpContext.Session.SetString("Pedidos", JsonConvert.SerializeObject(pedidos));

            ViewBag.PublicKey = _configuration["MercadoPago:PublicKey"];
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> InsertEnvioPedido([FromBody] EnvioPedidoViewModel model)
        {
            string urlAPI = _configuration["UrlAPI"];
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(urlAPI);

                // Insertar Envio
                var responseEnvio = await client.PostAsJsonAsync("envio/Insert", model.Envio);
                if (!responseEnvio.IsSuccessStatusCode)
                {
                    return BadRequest("Error al insertar el envío.");
                }

                // Insertar Pedido
                var responsePedido = await client.PostAsJsonAsync("envio/Insert", model.Pedido);
                if (!responsePedido.IsSuccessStatusCode)
                {
                    return BadRequest("Error al insertar el pedido.");
                }

                return Ok("Envío y Pedido creados con éxito.");
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetAllEnvios(string searchId)
        {
            List<Envio> envios = new List<Envio>();
            string urlAPI = _configuration["UrlAPI"];
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(urlAPI);
                var response = await client.GetAsync("Envio/GetAll");
                if (response.IsSuccessStatusCode)
                {
                    var resultString = await response.Content.ReadAsStringAsync();
                    envios = JsonConvert.DeserializeObject<List<Envio>>(resultString);
                }
                else
                {
                    // Manejar el caso donde la respuesta no es exitosa
                    return View("Error", new ErrorViewModel { RequestId = "Error al obtener los envíos" });
                }
            }

            ViewBag.SearchId = searchId;  // Pasar el valor de searchId a la vista
            return View("Gestion_Envios", envios);
        }



        [HttpGet]
        public async Task<IActionResult> GetEnviosByUserId()
        {
            List<Envio> envios = new List<Envio>();
            try
            {
                var userIdClaim = User.Claims.FirstOrDefault(c => c.Type == "UserId")?.Value;
                if (userIdClaim == null)
                {
                    return Unauthorized(new { success = false, message = "User not authenticated." });
                }

                if (!int.TryParse(userIdClaim, out int userId))
                {
                    return BadRequest(new { success = false, message = "Invalid User ID." });
                }

                string urlAPI = _configuration["UrlAPI"];
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(urlAPI);
                    var response = await client.GetAsync($"Envio/GetById?id={userId}");
                    if (response.IsSuccessStatusCode)
                    {
                        var resultString = await response.Content.ReadAsStringAsync();
                        envios = JsonConvert.DeserializeObject<List<Envio>>(resultString);
                    }
                }

                if (envios == null || !envios.Any())
                {
                    return NotFound(new { success = false, message = "No envios found for the user." });
                }
            }
            catch (Exception ex)
            {
                // Manejo de la excepción
                return StatusCode(500, new { success = false, message = "Internal server error.", details = ex.Message });
            }
            return Ok(envios);
        }

        [HttpPost]
        public async Task<IActionResult> InsertEnvio([FromBody] Envio envio)
        {
       
            var userIdClaim = User.Claims.FirstOrDefault(c => c.Type == "UserId")?.Value;

            if (userIdClaim == null)
            {
                return Unauthorized(new { success = false, message = "User not authenticated." });
            }

            if (int.TryParse(userIdClaim, out int userId))
            {
                envio.UsuarioId = userId;
            }
            else
            {
                return BadRequest(new { success = false, message = "Invalid User ID." });
            }

            string urlAPI = _configuration["UrlAPI"];
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(urlAPI);
                var response = await client.PostAsJsonAsync("envio/Insert", envio);
                if (response.IsSuccessStatusCode)
                {
                    return Ok(new { success = true });
                }
                return BadRequest(new { success = false });
            }
        }

        [HttpPut]
        public async Task<IActionResult> UpdateEnvio(int id, Envio envio)
        {
            string urlAPI = _configuration["UrlAPI"];
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(urlAPI);
                var response = await client.PutAsJsonAsync($"Envio/Update?id={id}", envio);
                if (response.IsSuccessStatusCode)
                {
                    return Ok();
                }
                return BadRequest();
            }
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteEnvio(int id)
        {
            string urlAPI = _configuration["UrlAPI"];
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(urlAPI);
                var response = await client.DeleteAsync($"envio/Delete?id={id}");
                if (response.IsSuccessStatusCode)
                {
                    return Ok();
                }
                return BadRequest();
            }
        }

        [HttpPost]
        public async Task<IActionResult> InsertPedido([FromBody] Pedido pedido)
        {
            var userIdClaim = User.Claims.FirstOrDefault(c => c.Type == "UserId")?.Value;

            if (userIdClaim == null)
            {
                return Unauthorized(new { success = false, message = "User not authenticated." });
            }

            if (!int.TryParse(userIdClaim, out int userId))
            {
                return BadRequest(new { success = false, message = "Invalid User ID." });
            }


            Cantidad = HttpContext.Session.GetInt32("Cantidad") ?? 0;
            Total = decimal.Parse(HttpContext.Session.GetString("Total"));
            var pedidos = JsonConvert.DeserializeObject<List<Pedido>>(HttpContext.Session.GetString("Pedidos"));

            // Asignar valores necesarios
            if (pedidos != null && pedidos.Any())
            {

                string urlAPI = _configuration["UrlAPI"]; // Asegúrate de que esta clave esté en tu appsettings.json

                foreach (var individualPedido in pedidos)
                {
                    individualPedido.UsuarioId = userId;
                    individualPedido.FechaPedido = DateTime.Now;
                    individualPedido.EstadoPedido = "Entrante";
                    individualPedido.IdEnvio = pedido.IdEnvio;


                    using (var client = new HttpClient())
                    {
                        client.BaseAddress = new Uri(urlAPI);
                        var response = await client.PostAsJsonAsync("Pedido/Insert", individualPedido);
                        if (!response.IsSuccessStatusCode)

INNOTEC-Proyect/Controllers/ProductController.cs
using INNOTEC_Proyect.Clases;
using INNOTEC_Proyect.Models;
using Microsoft.AspNetCore.Mvc;
using ML;
using Newtonsoft.Json;

namespace INNOTEC_Proyect.Controllers
{
    public class ProductController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IWebHostEnvironment _environment;

        public ProductController(IConfiguration configuration, IWebHostEnvironment hostingEnvironment)
        {
            _configuration = configuration;
            _environment = hostingEnvironment;
        }

        [HttpGet]
        public async Task<List<ML.Producto>> GetAll()
        {
            List<ML.Producto> productos = new List<ML.Producto>();
            string urlAPI = _configuration["UrlAPI"];
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(urlAPI);
                var response = await client.GetAsync("Producto/GetAll");
                if (response.IsSuccessStatusCode)
                {
                    var resultString = await response.Content.ReadAsStringAsync();
                    productos = JsonConvert.DeserializeObject<List<ML.Producto>>(resultString, new JsonSerializerSettings
                    {
                        Converters = new List<JsonConverter> { new NestedConverter() }
                    });
                }
                return productos;
            }
        }

        [HttpGet]
        public async Task<List<Departamento>> GetnavMenu()
        {
            List<Departamento> menuItems = new List<Departamento>();
            string urlAPI = _configuration["UrlAPI"];
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(urlAPI);
                var response = await client.GetAsync("Departamento/GetMenu");
                if (response.IsSuccessStatusCode)
                {
                    var jsonString = await response.Content.ReadAsStringAsync();
                    JsonSerializerSettings settings = new JsonSerializerSettings { Converters = new List<JsonConverter> { new NestedConverter() } };
                    menuItems = JsonConvert.DeserializeObject<List<Departamento>>(jsonString, settings);
                }
            }
            return menuItems;
        }

        [HttpGet]
        public async Task<IActionResult> Products(int page = 1, int pageSize = 8)
        {

            var productos = await GetAll();
            var menuItems = await GetnavMenu();

            var paginatedProducts = productos.Skip((page - 1) * pageSize).Take(pageSize).ToList();


            var viewModel = new HomeViewModel
            {
                MenuItems = menuItems,
                Productos = paginatedProducts,
                CurrentPage = page,
                TotalPages = (int)Math.Ceiling(productos.Count / (double)pageSize)

            };

            return View("~/Views/Products/Products.cshtml", viewModel);
        }
    }
}

INNOTEC-Proyect/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - INNOTEC_Proyect</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <!-- Custom site CSS -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/Images/logo.jpg" alt="Logo" height="80">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
@*                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Products">Productos</a>
                        </li>
                        @if (User.IsInRole("1") || User.IsInRole("2") || User.IsInRole("4"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" href="#" id="adminDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Gestión/Administración
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="adminDropdown">
                                    @if (User.IsInRole("1"))
                                    {
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="Index">Gestión de Usuarios</a></li>
                                    }
                                    @if (User.IsInRole("1") || User.IsInRole("2") || User.IsInRole("4"))
                                    {
                                        <a class="dropdown-item" asp-area="" asp-controller="Capturista" asp-action="Capturista">Gestión de productos</a>
                                    }
                                    @if (User.IsInRole("1") || User.IsInRole("4"))
                                    {
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Envio" asp-action="GetAllPedidos">Gestión de Envíos</a></li>
                                    }
                                </ul>
                            </li>
                        }
                    </ul>
                    <div class="navbar-nav ms-auto d-flex align-items-center">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                @if (User.Identity.IsAuthenticated)
                                {
                                    var userIdClaim = User.FindFirst("UserId");
                                    if (userIdClaim != null)
                                    {
                                        int idUsuario = int.Parse(userIdClaim.Value);
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Carrito" asp-action="GetByUserId" asp-route-idUsuario="@idUsuario">Carrito de compras</a>
                                    </li>
                                    }
                                }
                                else
                                {
                                <a class="nav-link text-dark" href="@Url.Action("Login", "Login")">
                                    <img src="~/images/usuario.png" alt="Profile Picture" class="rounded-circle" height="40">
                                </a>
                                }
                            </li>
                            <div class="dropdown">
                                <a class="nav-link text-dark dropdown-toggle" href="#" id="profileDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <img src="~/images/usuario.png" alt="Profile Picture" class="rounded-circle" height="40">
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="profileDropdown">
                                    <li><a class="dropdown-item" asp-controller="User" asp-action="Edit">Edit Profile</a></li>
                                    <li>
                                        <form method="post" asp-controller="Login" asp-action="Logout" class="dropdown-item">
                                            <button type="submit" class="btn btn-link p-0 m-0 align-baseline">Logout</button>
                                        </form>
                                    </li>
                                </ul>
                            </div>
                        }
                        else
                        {
                            <a class="nav-link text-dark" href="@Url.Action("Login", "Login")">
                                <img src="~/images/usuario.png" alt="Profile Picture" class="rounded-circle" height="40">
                            </a>
                        }
                    </div>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="footer-bottom">
            &copy; 2024 - INNOTEC_Proyect - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
        <div class="container">
            <div class="footer-content">
                <div class="column">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="footerDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                        Más información
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="footerDropdown">
                        <div class="row">
                            <div class="col-md-4">
                                <h6>Mensaje de Privacidad</h6>
                                <p>&copy; 2024 - INNOTEC_Proyect - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></p>
                            </div>
                            <div class="col-md-4">
                                <h6>Visítanos</h6>
                                <p><a href="https://www.google.com/maps/place/Universidad+Multicultural+CUDEC" target="_blank">En donde nos ubicamos</a></p>
                            </div>
                            <div class="col-md-4">
                                <h6>Nuestras Redes</h6>
                                <div class="social-links">
                                    <a href="https://www.facebook.com/ProDiesel4C?mibextid=ZbWKwL" target="_blank">
                                        <img src="~/images/iconFb.jpg" alt="Facebook" class="social-icon" style="width: 32px; height: 32px;">
                                    </a>
                                    <a href="https://www.instagram.com/prodiesel4c?utm_source=qr&igsh=aWR2OGkwbDN3NWM=" target="_blank">
                                        <img src="~/images/iconIg.jpg" alt="Instagram" class="social-icon" style="width: 32px; height: 32px;">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery, necessary for Bootstrap's JavaScript plugins -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- Bootstrap Bundle JS includes Popper -->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>