INNOTEC-Proyect/Controllers/CarritoController.cs
using INNOTEC_Proyect.Clases;
using Microsoft.AspNetCore.Mvc;
using ML;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net.Http.Headers;

namespace INNOTEC_Proyect.Controllers
{
    public class CarritoController : Controller
    {
        private readonly IConfiguration _configuration;

        public CarritoController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        [HttpPost]
        public async Task<IActionResult> AddCarrito(int idProducto)
        {
            var userIdClaim = User.FindFirst("UserId");
            if (userIdClaim == null)
            {
                return Json(new { success = false, message = "Usuario no autenticado" });
            }

            int idUsuario = int.Parse(userIdClaim.Value);

            ML.Result result = new ML.Result();
            try
            {
                using (HttpClient httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    string urlAPI = _configuration["UrlAPI"];
                    httpClient.BaseAddress = new Uri(urlAPI);

                    var requestUrl = $"Compra/Insert?idUsuario={idUsuario}&idProducto={idProducto}";
                    var response = await httpClient.PostAsync(requestUrl, null);

                    var readContent = await response.Content.ReadAsStringAsync();

                    if (response.IsSuccessStatusCode)
                    {
                        result.Success = bool.TryParse(readContent, out bool isSuccess) && isSuccess;
                    }
                    else
                    {
                        result.Success = false;
                        result.ErrorMessage = readContent;
                    }
                }
            }
            catch (Exception ex)
            {
                result.Success = false;
                result.ErrorMessage = ex.Message;
            }

            return Json(new { success = result.Success, message = result.Success ? "Producto agregado correctamente" : result.ErrorMessage });
        }

        [HttpGet]
        public async Task<IActionResult> GetByUserId(int idUsuario)
        {
            List<Compra> compras = new List<Compra>();
            try
            {
                using (HttpClient httpClient = new HttpClient())
                {
                    string urlAPI = _configuration["UrlAPI"];
                    httpClient.BaseAddress = new Uri(urlAPI);

                    var response = await httpClient.GetAsync($"Compra/GetByUserId?id={idUsuario}");
                    var readContent = await response.Content.ReadAsStringAsync();

                    if (response.IsSuccessStatusCode)
                    {
                        var jsonArray = JArray.Parse(readContent);
                        compras = jsonArray.Select(json => new Compra
                        {
                            IdCompra = (int)json["idCompra"],
                            Cantidad = (int)json["cantidad"],
                            FechaDeCompra = DateOnly.Parse(json["fechaDeCompra"].ToString()),
                            FechaVencimiento = DateOnly.Parse(json["fechaVencimiento"].ToString()),
                            Idproducto = (int)json["idProducto"],
                            IdproductoNavigation = new Producto
                            {
                                Nombre = (string)json["nombreProducto"],
                                DescripcionDelProducto = (string)json["descripcionProducto"],
                                Precio = json["precio"] != null ? (int)json["precio"] : 0,
                                ImagenDelProducto = json["imagenProducto"] != null ? Convert.FromBase64String(json["imagenProducto"].ToString()) : null
                            }
                        }).ToList();
                    }
                }
            }
            catch (Exception ex)
            {
                // Manejo del error
            }

            return View(compras);
        }

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            ML.Result result = new ML.Result();
            try
            {
                using (HttpClient httpClient = new HttpClient())
                {
                    string urlAPI = _configuration["UrlAPI"];
                    httpClient.BaseAddress = new Uri(urlAPI);
                    httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    var response = await httpClient.GetAsync("Compra/GetAll");
                    var readContent = await response.Content.ReadAsStringAsync();

                    if (response.IsSuccessStatusCode)
                    {
                        var compras = JsonConvert.DeserializeObject<List<Compra>>(readContent);
                        result.Results = compras.Cast<object>().ToList();
                        result.Success = true;
                    }
                    else
                    {
                        result.Success = false;
                        result.ErrorMessage = readContent;
                    }
                }
            }
            catch (Exception ex)
            {
                result.Success = false;
                result.ErrorMessage = ex.Message;
            }

            return View(result.Results);
        }

        [HttpGet]
        public async Task<IActionResult> GetById(int id)
        {
            ML.Result result = new ML.Result();
            try
            {
                using (HttpClient httpClient = new HttpClient())
                {
                    string urlAPI = _configuration["UrlAPI"];
                    httpClient.BaseAddress = new Uri(urlAPI);
                    httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    var response = await httpClient.GetAsync($"Compra/GetById?id={id}");
                    var readContent = await response.Content.ReadAsStringAsync();

                    if (response.IsSuccessStatusCode)
                    {
                        result.Object = JsonConvert.DeserializeObject<Compra>(readContent);
                        result.Success = true;
                    }
                    else
                    {
                        result.Success = false;
                        result.ErrorMessage = readContent;
                    }
                }
            }
            catch (Exception ex)
            {
                result.Success = false;
                result.ErrorMessage = ex.Message;
            }

            return View(result.Object);
        }

        [HttpPut]
        public async Task<IActionResult> Update([FromBody] Compra compra)
        {
            ML.Result result = new ML.Result();
            try
            {
                using (HttpClient httpClient = new HttpClient())
                {
                    string urlAPI = _configuration["UrlAPI"];
                    httpClient.BaseAddress = new Uri(urlAPI);
                    httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    var jsonContent = JsonConvert.SerializeObject(compra);
                    var content = new StringContent(jsonContent, System.Text.Encoding.UTF8, "application/json");

                    var response = await httpClient.PutAsync("Compra/Update", content);
                    var readContent = await response.Content.ReadAsStringAsync();

                    if (response.IsSuccessStatusCode)
                    {
                        result.Success = true;
                    }
                    else
                    {
                        result.Success = false;
                        result.ErrorMessage = readContent;
                    }
                }
            }
            catch (Exception ex)
            {
                result.Success = false;
                result.ErrorMessage = ex.Message;
            }

            return Json(result);
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            ML.Result result = new ML.Result();
            try
            {
                using (HttpClient httpClient = new HttpClient())
                {
                    string urlAPI = _configuration["UrlAPI"];
                    httpClient.BaseAddress = new Uri(urlAPI);
                    httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    var response = await httpClient.DeleteAsync($"Compra/Delete?id={id}");
                    var readContent = await response.Content.ReadAsStringAsync();

                    if (response.IsSuccessStatusCode)
                    {
                        result.Success = true;
                    }
                    else
                    {
                        result.Success = false;
                        result.ErrorMessage = readContent;
                    }
                }
            }
            catch (Exception ex)
            {
                result.Success = false;
                result.ErrorMessage = ex.Message;
            }

            return Json(result);
        }

        [HttpGet]
        public async Task<List<Departamento>> GetnavMenu()
        {
            List<Departamento> menuItems = new List<Departamento>();
            string urlAPI = _configuration["UrlAPI"];
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(urlAPI);
                var response = await client.GetAsync("Departamento/GetMenu");
                if (response.IsSuccessStatusCode)
                {

INNOTEC-Proyect/Views/Carrito/Carrito.cshtml
@* @model List<ML.Compra>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Lista de Compras";
}
@section Styles {
    <link rel="stylesheet" href="~/css/stylecarrito.css" asp-append-version="true" />
}

<div class="container">
    @foreach (var item in Model)
    {
        <div class="row mb-3 p-2 bg-white border rounded">
            <div class="col-md-2 mt-1">
                <img class="img-fluid img-responsive rounded product-image" src="@item.IdproductoNavigation?.ImagenDelProducto ?? Url.Content(" ~ /images/no-image-available.png")">
            </div>
            <div class="col-md-6 mt-1">
                <h5>@item.IdproductoNavigation?.Nombre</h5>
                <div class="d-flex flex-row">
                    <div class="ratings mr-2"><i class="fa fa-star"></i></div><span>@item.FechaDeCompra?.ToString("yyyy-MM-dd")</span>
                </div>
                <p class="text-justify text-truncate para mb-0">@item.IdproductoNavigation?.DescripcionDelProducto</p>
            </div>
            <div class="col-md-4 align-items-center align-content-center">
                <div class="d-flex flex-row align-items-center">
                    <h4 class="mr-1">$@item.IdproductoNavigation?.Precio</h4>
                </div>
                <div class="d-flex flex-column mt-4">
                    <button class="btn btn-primary btn-sm" type="button">Detalles</button>
                    <button class="btn btn-outline-primary btn-sm mt-2" type="button">Guardar para más tarde</button>
                </div>
            </div>
        </div>
    }
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.cantidad').on('change', function () {
                var id = $(this).data('id');
                var cantidad = $(this).val();
                $.post('@Url.Action("UpdateCantidad", "Carrito")', { id: id, cantidad: cantidad })
                    .done(function (response) {
                        location.reload(); 
                    })
                    .fail(function (error) {
                        alert('Error al actualizar la cantidad');
                    });
            });

            $('.delete-btn').click(function () {
                var id = $(this).data('id');
                $.post('@Url.Action("Delete", "Carrito")', { id: id })
                    .done(function (response) {
                        location.reload(); 
                    })
                    .fail(function (error) {
                        alert('Error al eliminar el producto');
                    });
            });

            $('.save-btn').click(function () {
                var id = $(this).data('id');
                var cantidad = $(this).closest('tr').find('.cantidad').val();
                $.post('@Url.Action("UpdateCantidad", "Carrito")', { id: id, cantidad: cantidad })
                    .done(function (response) {
                        alert('Cantidad actualizada');
                    })
                    .fail(function (error) {
                        alert('Error al guardar los cambios');
                    });
            });
        });
    </script>
} *@

INNOTEC-Proyect/Views/Carrito/GetByUserId.cshtml
@using System.Security.Claims
@model List<ML.Compra>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Lista de Compras";
}
@section Styles {
    <link rel="stylesheet" href="~/css/stylecarrito.css" asp-append-version="true" />
}

<div class="container">
    <div class="row">
        <div class="col-lg-8">
            @foreach (var item in Model)
            {
                <div class="row mb-3 p-2 bg-white border rounded">
                    <div class="col-md-2 mt-1">
                        @if (item.IdproductoNavigation?.ImagenDelProducto != null)
                        {
                            <img class="img-fluid img-responsive rounded product-image" src="data:image/jpeg;base64,@Convert.ToBase64String(item.IdproductoNavigation?.ImagenDelProducto)" alt="@item.IdproductoNavigation?.Nombre">
                        }
                        else
                        {
                            <img src="~/Images/no-image-available.png" alt="No image available" class="img-responsive" />
                        }
                    </div>
                    <div class="col-md-6 mt-1">
                        <h5>@item.IdproductoNavigation?.Nombre</h5>
                        <div class="d-flex flex-row">
                            <div class="ratings mr-2"><i class="fa fa-star"></i></div><span>@item.FechaDeCompra?.ToString("yyyy-MM-dd")</span>
                        </div>
                        <p class="text-justify text-truncate para mb-0">@item.IdproductoNavigation?.DescripcionDelProducto</p>
                    </div>
                    <div class="col-md-4 align-items-center align-content-center">
                        <div class="d-flex flex-row align-items-center">
                            <h4 class="mr-1">$@(item.IdproductoNavigation?.Precio * item.Cantidad)</h4>

                        </div>
                        <div class="d-flex flex-column mt-4">
                            <input type="hidden" class="form-control idusuario" value="@User.FindFirstValue("UserId")" />
                            <input type="hidden" class="form-control idproducto" value="@item.Idproducto" />
                            <input type="hidden" class="form-control idcompra" value="@item.IdCompra" />
                            <input type="number" class="form-control mb-2 cantidad" value="@item.Cantidad" data-id="@item.IdCompra" min="1" />
                            <button class="btn btn-outline-danger btn-sm eliminar-btn" type="button" data-id="@item.IdCompra">Eliminar</button>
                            <button class="btn btn-outline-primary btn-sm mt-2 comprar-btn" type="button" data-id="@item.IdCompra" data-total=@(item.IdproductoNavigation?.Precio * item.Cantidad)>Comprar ahora</button>
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="col-lg-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Resumen de compra</h5>
                    <p class="card-text">Total productos: @Model.Count</p>
                    <p class="card-text">Envío: Gratis</p>
                    <p class="card-text">Total: $<span id="total-compra">@Model.Sum(item => item.IdproductoNavigation?.Precio * item.Cantidad)</span></p>
                    <button id="continuar-compra" class="btn btn-primary btn-block">Continuar compra</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/js/carrito.js?v=@DateTime.Now.Ticks"></script>